const int DZBBC_INACTIVE = 0;
const int DZBBC_ANNOUNCED = 1;
const int DZBBC_CRASHSITE_ACTIVE = 2;
const int DZBBC_FACTION_FIGHT_ACTIVE = 3;
const int DZBBC_PLAYER_DETECTED = 4;
const int DZBBC_COMBAT_ACTIVE = 5;
const int DZBBC_COMBAT_COMPLETE = 6;
const int DZBBC_BLACKBOX_SIGNAL_FOUND = 7;
const int DZBBC_BLACKBOX_HACK_ACTIVE = 8;
const int DZBBC_BLACKBOX_HACK_COMPLETE = 9;
const int DZBBC_DATACORE_EXTRACTED = 10;
const int DZBBC_DATACORE_TRANSPORT_ACTIVE = 11;
const int DZBBC_DATACORE_EXPIRED = 12;
const int DZBBC_TERMINAL_FOUND = 13;
const int DZBBC_TERMINAL_DECRYPT_ACTIVE = 14;
const int DZBBC_FINAL_DEFENSE_ACTIVE = 15;
const int DZBBC_TERMINAL_DECRYPT_COMPLETE = 16;
const int DZBBC_REWARD_UNLOCKED = 17;
const int DZBBC_GASZONE_FLARE_TAKEN = 18;
const int DZBBC_COMPLETED = 19;
const int DZBBC_FAILED = 20;
const int DZBBC_CLEANUP = 21;

class DZBBC_EventStateNames
{
	static string GetName(int state)
	{
		if (state == DZBBC_INACTIVE) return "INACTIVE";
		if (state == DZBBC_ANNOUNCED) return "ANNOUNCED";
		if (state == DZBBC_CRASHSITE_ACTIVE) return "CRASHSITE_ACTIVE";
		if (state == DZBBC_FACTION_FIGHT_ACTIVE) return "FACTION_FIGHT_ACTIVE";
		if (state == DZBBC_PLAYER_DETECTED) return "PLAYER_DETECTED";
		if (state == DZBBC_COMBAT_ACTIVE) return "COMBAT_ACTIVE";
		if (state == DZBBC_COMBAT_COMPLETE) return "COMBAT_COMPLETE";
		if (state == DZBBC_BLACKBOX_SIGNAL_FOUND) return "BLACKBOX_SIGNAL_FOUND";
		if (state == DZBBC_BLACKBOX_HACK_ACTIVE) return "BLACKBOX_HACK_ACTIVE";
		if (state == DZBBC_BLACKBOX_HACK_COMPLETE) return "BLACKBOX_HACK_COMPLETE";
		if (state == DZBBC_DATACORE_EXTRACTED) return "DATACORE_EXTRACTED";
		if (state == DZBBC_DATACORE_TRANSPORT_ACTIVE) return "DATACORE_TRANSPORT_ACTIVE";
		if (state == DZBBC_DATACORE_EXPIRED) return "DATACORE_EXPIRED";
		if (state == DZBBC_TERMINAL_FOUND) return "TERMINAL_FOUND";
		if (state == DZBBC_TERMINAL_DECRYPT_ACTIVE) return "TERMINAL_DECRYPT_ACTIVE";
		if (state == DZBBC_FINAL_DEFENSE_ACTIVE) return "FINAL_DEFENSE_ACTIVE";
		if (state == DZBBC_TERMINAL_DECRYPT_COMPLETE) return "TERMINAL_DECRYPT_COMPLETE";
		if (state == DZBBC_REWARD_UNLOCKED) return "REWARD_UNLOCKED";
		if (state == DZBBC_GASZONE_FLARE_TAKEN) return "GASZONE_FLARE_TAKEN";
		if (state == DZBBC_COMPLETED) return "COMPLETED";
		if (state == DZBBC_FAILED) return "FAILED";
		if (state == DZBBC_CLEANUP) return "CLEANUP";
		return "UNKNOWN";
	}
}
