static const int DZP_PROTOCOL_VERSION = 3;
static const int DZP_PROPERTY_MENU_ID = 1701170199;

enum DZ_PROPERTYZ_RPC
{
    REQUEST_PROPERTY = 1701170100,
    PROPERTY_RESPONSE,
    BUY_PROPERTY,
    SELL_PROPERTY,
    TOGGLE_DOOR_LOCK,
    RESULT_MESSAGE,
    REQUEST_STORAGE,
    STORAGE_RESPONSE,
    STORE_HAND_ITEM,
    WITHDRAW_STORAGE_ITEM,
    REQUEST_OWNED_PROPERTIES,
    OWNED_PROPERTIES_RESPONSE
}

enum DZP_STORAGE_CATEGORY
{
    GENERAL = 0,
    WEAPON,
    BARREL,
    SEA_CHEST,
    WOODEN_CRATE
}
