name = "DeutschZ UiAdminZ";
picture = "";
logo = "";
logoSmall = "";
logoOver = "";
tooltip = "DeutschZ UiAdminZ";
overview = "Optionale serverautorisierte DeutschZ Event-Admin-Oberflaeche mit Admin Lite und gesperrter Pro-Shell.";
author = "DeutschZ";
version = "2.0.0-admin-pro-shell";
